### ISSUE TITLE
Root directory is not used

### ISSUE THREAD

**Issue by maxmeyer** [davinche/gmux#11]
# Description

Given a project configuration file:
~~~
{
  "Name": "aruba",
  "Root": "~/data/projects/aruba",
  "Windows": [
    {
      "Name": "editor",
      "Layout": "main-vertical",
      "Panes": [
        "zsh"
      ]
    }
  ]
}
~~~
When I run `gmux start aruba`
Then I want a session to be started with "~/data/projects/aruba" as root directory

=> But it's started with `~/`

# Expected behaviour

I would to see `gmux` picking up root option.

**Comment by maxmeyer** [comment]
After killing tmux and start it again. It works. That's weird.

**Comment by davinche** [comment]
This was an issue reported before that should've been fixed with the latest version of gmux. Please feel free to reopen if this is still an issue.

**Comment by maxmeyer** [comment]
Ok. Thanks.
