### ISSUE TITLE
Output tmux command if debug option is given

### ISSUE THREAD

**Issue by maxmeyer** [davinche/gmux#12]
# Description

I would like to see which kind of tmux-command is used, when running `gmux start` to troubleshoot isses. Now there's no option - at least there's no help entry for that

# Expected behaviour

~~~bash
gmux start <project> -d
gmux start <project> --debug
~~~

output something like

~~~
tmux new-session [...]
~~~

**Comment by davinche** [comment]
You can pass in the `-d, --debug` global option before running the command. Eg: `gmux --debug start myproject`. It will print out the tmux commands before attaching to the session.

**Comment by maxmeyer** [comment]
Ah. Sorry I didn't see that.
