### ISSUE TITLE
Don't attach project on start

### ISSUE THREAD

**Issue by maxmeyer** [davinche/gmux#8]
# Description

`tmuxinator` allows users to start a session "detached" this is quite helpful when one wants to run a script to setup tmux sessions.

When you start a session with out that option, it's not possible to run start in a script to create them in background.

# Expected behaviour

Having a `attach` option would like [tmuxinator](https://github.com/tmuxinator/tmuxinator/blob/6dd39bcb3c6502c7f5dac811e87e769d63baf7f2/lib/tmuxinator/assets/template.erb#L88). would is possible to use gmux in setup scripts.

**Comment by davinche** [comment]
Good call regarding the usage in setup scripts. I will add this feature this weekend.

**Comment by maxmeyer** [comment]
👍

**Comment by davinche** [comment]
Added the attach option. Available now: https://github.com/davinche/gmux/releases/tag/v0.1.4
Please reopen if you find any issues with it. Thanks.

**Comment by maxmeyer** [comment]
Thanks.
